<<<<<<< HEAD
# Generated by Django 4.0.6 on 2022-07-20 14:05
=======
# Generated by Django 3.2.14 on 2022-07-20 14:09
>>>>>>> upstream/developer

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newword',
            name='like_user_ids',
<<<<<<< HEAD
            field=models.ManyToManyField(null=True, related_name='likeword', to=settings.AUTH_USER_MODEL),
=======
            field=models.ManyToManyField(blank=True, related_name='likeword', to=settings.AUTH_USER_MODEL),
>>>>>>> upstream/developer
        ),
    ]
